import { Daytona } from "@daytona/sdk";
import FormData from "form-data";
void FormData;
import type { Campaign, Creative, ProductBrief } from "../types";
import { providerMode } from "../env";
import { savePackPreviewHtml, savePackZip } from "../store";

export type DaytonaPackResult = {
  mode: "live" | "mock";
  sandboxId?: string;
  previewUrl?: string;
  zipPath?: string;
  zipReady: boolean;
  logs: string[];
  mock: boolean;
};

function buildFiles(
  brief: ProductBrief,
  campaign: Campaign,
  creatives: Creative[],
) {
  const readme = `# ${brief.name} (Zalet pack)

Generated by Zalet (Firecrawl · Exa · xAI/Grok · Fal · Daytona · Convex)

## Positioning
${campaign.positioning}

## 7-day plan
${campaign.week
  .map(
    (d) =>
      `- Day ${d.day} · ${d.platform} · ${d.angle}\n  Hook: ${d.hook}\n  CTA: ${d.cta} · KPI: ${d.kpi}`,
  )
  .join("\n")}

## Scripts
${campaign.scripts
  .map(
    (s) =>
      `### Day ${s.dayRef} (${s.language})\nHook: ${s.hookText}\n` +
      s.beats.map((b) => `- [${b.t}s] ${b.vo} | ${b.onScreen}`).join("\n"),
  )
  .join("\n\n")}
`;

  const strategy = JSON.stringify({ brief, campaign, creatives }, null, 2);
  const indexHtml = `<!doctype html>
<html><head><meta charset="utf-8"/><title>${brief.name} · Zalet</title>
<style>
body{margin:0;font-family:ui-sans-serif,system-ui;background:#14110e;color:#f4efe6}
main{max-width:880px;margin:0 auto;padding:32px}
h1{font-size:40px;letter-spacing:-.03em}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:24px}
.card{border:1px solid #3a322a;border-radius:14px;padding:14px;background:#1c1814}
img{width:100%;border-radius:10px}
.muted{color:#b9a994}
</style></head>
<body><main>
<p class="muted">Packed inside Daytona sandbox</p>
<h1>${brief.name}</h1>
<p>${campaign.positioning}</p>
<div class="grid">
${campaign.week
  .map(
    (d) =>
      `<div class="card"><strong>Day ${d.day}</strong><div class="muted">${d.platform}</div><p>${d.hook}</p></div>`,
  )
  .join("")}
</div>
<div class="grid" style="margin-top:20px">
${creatives
  .map((c) =>
    c.url.startsWith("data:")
      ? `<div class="card"><div class="muted">still</div><p>${c.prompt.slice(0, 80)}</p></div>`
      : `<div class="card"><img src="${c.url}" alt="creative"/></div>`,
  )
  .join("")}
</div>
</main></body></html>`;

  return { readme, strategy, indexHtml };
}

async function zipBuffers(files: {
  readme: string;
  strategy: string;
  indexHtml: string;
}): Promise<Buffer> {
  return zipWithStore(files);
}

/** Minimal ZIP (store only) without extra deps. */
function zipWithStore(files: {
  readme: string;
  strategy: string;
  indexHtml: string;
}): Buffer {
  const entries: { name: string; data: Buffer }[] = [
    { name: "README.md", data: Buffer.from(files.readme, "utf8") },
    { name: "strategy.json", data: Buffer.from(files.strategy, "utf8") },
    { name: "index.html", data: Buffer.from(files.indexHtml, "utf8") },
  ];

  const parts: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;

  for (const e of entries) {
    const nameBuf = Buffer.from(e.name, "utf8");
    const local = Buffer.alloc(30 + nameBuf.length);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0, 6);
    local.writeUInt16LE(0, 8); // store
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0, 12);
    local.writeUInt32LE(crc32(e.data), 14);
    local.writeUInt32LE(e.data.length, 18);
    local.writeUInt32LE(e.data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28);
    nameBuf.copy(local, 30);

    parts.push(local, e.data);

    const cen = Buffer.alloc(46 + nameBuf.length);
    cen.writeUInt32LE(0x02014b50, 0);
    cen.writeUInt16LE(20, 4);
    cen.writeUInt16LE(20, 6);
    cen.writeUInt16LE(0, 8);
    cen.writeUInt16LE(0, 10);
    cen.writeUInt16LE(0, 12);
    cen.writeUInt16LE(0, 14);
    cen.writeUInt32LE(crc32(e.data), 16);
    cen.writeUInt32LE(e.data.length, 20);
    cen.writeUInt32LE(e.data.length, 24);
    cen.writeUInt16LE(nameBuf.length, 28);
    cen.writeUInt16LE(0, 30);
    cen.writeUInt16LE(0, 32);
    cen.writeUInt16LE(0, 34);
    cen.writeUInt16LE(0, 36);
    cen.writeUInt32LE(0, 38);
    cen.writeUInt32LE(offset, 42);
    nameBuf.copy(cen, 46);
    central.push(cen);

    offset += local.length + e.data.length;
  }

  const centralBuf = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBuf.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);

  return Buffer.concat([...parts, centralBuf, end]);
}

function crc32(buf: Buffer): number {
  let c = ~0;
  for (let i = 0; i < buf.length; i++) {
    c ^= buf[i]!;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? (c >>> 1) ^ 0xedb88320 : c >>> 1;
    }
  }
  return ~c >>> 0;
}

export async function packInDaytona(opts: {
  runId: string;
  brief: ProductBrief;
  campaign: Campaign;
  creatives: Creative[];
}): Promise<DaytonaPackResult> {
  const mode = providerMode().daytona;
  const files = buildFiles(opts.brief, opts.campaign, opts.creatives);
  const logs: string[] = [];

  // Always keep a local preview + zip so the board can download even if sandbox dies.
  await savePackPreviewHtml(opts.runId, files.indexHtml);
  const localZip = await zipBuffers(files);
  const zipPath = await savePackZip(opts.runId, localZip);
  logs.push(`$ local pack → ${zipPath}`);

  const localPreview = `/api/runs/${opts.runId}/preview`;

  if (mode === "mock") {
    logs.push("$ # MOCK Daytona sandbox (DAYTONA_API_KEY missing)");
    logs.push("$ mkdir -p /tmp/zalet-campaign && cd /tmp/zalet-campaign");
    logs.push("$ cat > README.md strategy.json index.html");
    logs.push("$ zip -r campaign.zip README.md strategy.json index.html");
    logs.push("adding: README.md / strategy.json / index.html");
    logs.push("$ # serving via Zalet preview route");
    return {
      mode,
      sandboxId: "mock-sandbox",
      previewUrl: localPreview,
      zipPath,
      zipReady: true,
      logs,
      mock: true,
    };
  }

  const daytona = new Daytona({ apiKey: process.env.DAYTONA_API_KEY });
  const sandbox = await daytona.create();
  logs.push(`$ daytona.create() → ${sandbox.id}`);

  try {
    await sandbox.fs.createFolder("/home/daytona/zalet", "755");
    await sandbox.fs.uploadFile(
      Buffer.from(files.readme, "utf8"),
      "/home/daytona/zalet/README.md",
    );
    await sandbox.fs.uploadFile(
      Buffer.from(files.strategy, "utf8"),
      "/home/daytona/zalet/strategy.json",
    );
    await sandbox.fs.uploadFile(
      Buffer.from(files.indexHtml, "utf8"),
      "/home/daytona/zalet/index.html",
    );
    logs.push("$ uploaded README.md strategy.json index.html");

    const zip = await sandbox.process.executeCommand(
      `cd /home/daytona/zalet && python3 - <<'PY'
import zipfile
with zipfile.ZipFile('campaign.zip', 'w') as z:
    for name in ('README.md', 'strategy.json', 'index.html'):
        z.write(name)
print('zipped', z.filename)
PY
ls -la`,
    );
    logs.push("$ python3 zipfile → campaign.zip");
    if (zip.result) logs.push(String(zip.result).slice(0, 1500));

    try {
      const remoteZip = await sandbox.fs.downloadFile(
        "/home/daytona/zalet/campaign.zip",
      );
      await savePackZip(opts.runId, remoteZip);
      logs.push("$ downloaded campaign.zip from sandbox → local pack");
    } catch (err) {
      logs.push(
        `zip download skipped (using local zip): ${err instanceof Error ? err.message : "error"}`,
      );
    }

    let previewUrl: string | undefined = localPreview;
    const keepSandbox =
      process.env.DAYTONA_KEEP_SANDBOX === "1" ||
      process.env.DAYTONA_KEEP_SANDBOX === "true";

    if (keepSandbox) {
      try {
        await sandbox.process.executeCommand(
          "cd /home/daytona/zalet && nohup python3 -m http.server 3000 >/tmp/http.log 2>&1 & sleep 1",
        );
        const preview = await sandbox.getPreviewLink(3000);
        previewUrl =
          (preview as { url?: string }).url ||
          (preview as { link?: string }).link ||
          localPreview;
        logs.push(`$ preview → ${previewUrl}`);
      } catch (err) {
        logs.push(
          `preview skipped: ${err instanceof Error ? err.message : "error"}`,
        );
      }
    } else {
      try {
        await daytona.delete(sandbox);
        logs.push("$ daytona.delete() → sandbox cleaned up (zip kept locally)");
      } catch (err) {
        logs.push(
          `cleanup skipped: ${err instanceof Error ? err.message : "error"}`,
        );
      }
      logs.push(`$ local preview → ${localPreview}`);
    }

    return {
      mode: "live",
      sandboxId: keepSandbox ? sandbox.id : undefined,
      previewUrl,
      zipPath,
      zipReady: true,
      logs,
      mock: false,
    };
  } catch (err) {
    logs.push(
      `Daytona error: ${err instanceof Error ? err.message : "unknown"}`,
    );
    try {
      await daytona.delete(sandbox);
      logs.push("$ daytona.delete() after error");
    } catch {
      /* ignore */
    }
    return {
      mode: "mock",
      sandboxId: sandbox.id,
      previewUrl: localPreview,
      zipPath,
      zipReady: true,
      logs,
      mock: true,
    };
  }
}
