import { Daytona } from "@daytona/sdk";
import FormData from "form-data";
void FormData;
import type { Campaign, Creative, ProductBrief } from "../types";
import { providerMode } from "../env";

export type DaytonaPackResult = {
  mode: "live" | "mock";
  sandboxId?: string;
  previewUrl?: string;
  zipPath?: string;
  logs: string[];
  mock: boolean;
};

function buildFiles(
  brief: ProductBrief,
  campaign: Campaign,
  creatives: Creative[],
) {
  const readme = `# ${brief.name} (Zalet pack)

Generated by Zalet (Firecrawl · Exa · xAI/Grok · Fal · Daytona · Convex)

## Positioning
${campaign.positioning}

## 7-day plan
${campaign.week
  .map(
    (d) =>
      `- Day ${d.day} · ${d.platform} · ${d.angle}\n  Hook: ${d.hook}\n  CTA: ${d.cta} · KPI: ${d.kpi}`,
  )
  .join("\n")}

## Scripts
${campaign.scripts
  .map(
    (s) =>
      `### Day ${s.dayRef} (${s.language})\nHook: ${s.hookText}\n` +
      s.beats.map((b) => `- [${b.t}s] ${b.vo} | ${b.onScreen}`).join("\n"),
  )
  .join("\n\n")}
`;

  const strategy = JSON.stringify({ brief, campaign, creatives }, null, 2);
  const indexHtml = `<!doctype html>
<html><head><meta charset="utf-8"/><title>${brief.name} · Zalet</title>
<style>
body{margin:0;font-family:ui-sans-serif,system-ui;background:#14110e;color:#f4efe6}
main{max-width:880px;margin:0 auto;padding:32px}
h1{font-size:40px;letter-spacing:-.03em}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:24px}
.card{border:1px solid #3a322a;border-radius:14px;padding:14px;background:#1c1814}
img{width:100%;border-radius:10px}
.muted{color:#b9a994}
</style></head>
<body><main>
<p class="muted">Packed inside Daytona sandbox</p>
<h1>${brief.name}</h1>
<p>${campaign.positioning}</p>
<div class="grid">
${campaign.week
  .map(
    (d) =>
      `<div class="card"><strong>Day ${d.day}</strong><div class="muted">${d.platform}</div><p>${d.hook}</p></div>`,
  )
  .join("")}
</div>
<div class="grid" style="margin-top:20px">
${creatives
  .map((c) =>
    c.url.startsWith("data:")
      ? `<div class="card"><div class="muted">still</div><p>${c.prompt.slice(0, 80)}</p></div>`
      : `<div class="card"><img src="${c.url}" alt="creative"/></div>`,
  )
  .join("")}
</div>
</main></body></html>`;

  return { readme, strategy, indexHtml };
}

export async function packInDaytona(opts: {
  brief: ProductBrief;
  campaign: Campaign;
  creatives: Creative[];
}): Promise<DaytonaPackResult> {
  const mode = providerMode().daytona;
  const files = buildFiles(opts.brief, opts.campaign, opts.creatives);
  const logs: string[] = [];

  if (mode === "mock") {
    logs.push("$ # MOCK Daytona sandbox (DAYTONA_API_KEY missing)");
    logs.push("$ mkdir -p /tmp/zalet-campaign && cd /tmp/zalet-campaign");
    logs.push("$ cat > README.md strategy.json index.html");
    logs.push("$ zip -r campaign.zip README.md strategy.json index.html");
    logs.push("adding: README.md / strategy.json / index.html");
    logs.push("$ python3 -m http.server 3000");
    logs.push("Serving campaign board on preview (mock)");
    return {
      mode,
      sandboxId: "mock-sandbox",
      previewUrl: undefined,
      zipPath: "/tmp/zalet-campaign/campaign.zip",
      logs,
      mock: true,
    };
  }

  const daytona = new Daytona({ apiKey: process.env.DAYTONA_API_KEY });
  const sandbox = await daytona.create();
  logs.push(`$ daytona.create() → ${sandbox.id}`);

  try {
    await sandbox.fs.createFolder("/home/daytona/zalet", "755");
    await sandbox.fs.uploadFile(
      Buffer.from(files.readme, "utf8"),
      "/home/daytona/zalet/README.md",
    );
    await sandbox.fs.uploadFile(
      Buffer.from(files.strategy, "utf8"),
      "/home/daytona/zalet/strategy.json",
    );
    await sandbox.fs.uploadFile(
      Buffer.from(files.indexHtml, "utf8"),
      "/home/daytona/zalet/index.html",
    );
    logs.push("$ uploaded README.md strategy.json index.html");

    // Prefer python zipfile  -  many snapshots don't include the zip binary.
    const zip = await sandbox.process.executeCommand(
      `cd /home/daytona/zalet && python3 - <<'PY'
import zipfile
with zipfile.ZipFile('campaign.zip', 'w') as z:
    for name in ('README.md', 'strategy.json', 'index.html'):
        z.write(name)
print('zipped', z.filename)
PY
ls -la`,
    );
    logs.push("$ python3 zipfile → campaign.zip");
    if (zip.result) logs.push(String(zip.result).slice(0, 1500));

    let previewUrl: string | undefined;
    try {
      await sandbox.process.executeCommand(
        "cd /home/daytona/zalet && nohup python3 -m http.server 3000 >/tmp/http.log 2>&1 & sleep 1",
      );
      const preview = await sandbox.getPreviewLink(3000);
      previewUrl =
        (preview as { url?: string }).url ||
        (preview as { link?: string }).link;
      logs.push(`$ preview → ${previewUrl || "(no url field)"}`);
    } catch (err) {
      logs.push(
        `preview skipped: ${err instanceof Error ? err.message : "error"}`,
      );
    }

    return {
      mode: "live",
      sandboxId: sandbox.id,
      previewUrl,
      zipPath: "/home/daytona/zalet/campaign.zip",
      logs,
      mock: false,
    };
  } catch (err) {
    logs.push(
      `Daytona error: ${err instanceof Error ? err.message : "unknown"}`,
    );
    return {
      mode: "mock",
      sandboxId: sandbox.id,
      logs,
      mock: true,
    };
  }
}
